= Service Permissions
:!toc-title:
:!toc-placement:
:toc:

Set up your service with typical permissions used at Vy!

toc::[]

== About

This module will give you most of the basic permissions you need when setting up your service.
This includes SQS, SNS, DynamoDB, KMS and more!

Feel like something is missing?
Open a pull request or send a message on #team-infrastructure-public!

== Usage

Add the module directly in your microservice's infrastructure!

[source, hcl]
----
module "permissions" {
  source = "github.com/nsbno/terraform-aws-service-permissions?ref=x.y.z"

  role_arn = module.service.role_arn

  sqs_queues = [
    {
      arn = data.aws_sqs_queue.arn
      permissions = ["receive", "delete", "send"]
    }
  ]

  sns_topics = [
    {
      arn = data.aws_sns_topic.arn
      permissions = ["subscription", "publish"]
    }
  ]
}
----

== Available Services and Permissions

Here are all the services and permissions.

|===
|Service |Default Permissions |Optional Permissions |Description

1.3+|`sqs_queues`
1.3+|`sqs:GetQueueAttributes`
|`recieve`
|Recieve Messages from the queue
|`send`
|Send messages to the queue
|`delete`
|Delete messages from the queue

1.2+|`sns_topics`
1.2+|None
|`publish`
|Publish a message to the topic
|`subscription`
|Manage your subscriptions to the topic (subscribe, unsubscribe)
|===

== Relevant Repositories

Here are some relevant repositories that can be used together with this module!

* link:https://github.com/nsbno/terraform-aws-ecs-service[`nsbno/terraform-aws-ecs-service`] - Create an ECS Service!
