version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

terraform_versions: &terraform_versions
  - 1.0.11
  - 1.1.4
  - 1.2.5

terraform_folders: &terraform_folders
  - ./
  - ./examples/simple/

workflows:
  validate:
    jobs:
      - terraform/validate:
          checkout: true
          backend: false
          matrix:
            parameters:
              tag: *terraform_versions
              path: *terraform_folders
